apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "syvora-app.fullname" . }}
  labels:
    app: {{ include "syvora-app.name" . }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ include "syvora-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "syvora-app.name" . }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 20

